FROM ubuntu:20.04
ARG blast_version=2.15.0
ARG vdb_version=3.0.8
ARG num_procs=4

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul

RUN mkdir -p /blast/bin /blast/lib

RUN apt-get -y -m update && \
    apt-get -y upgrade && \
    apt-get install -y curl libxml-simple-perl libwww-perl libnet-perl build-essential software-properties-common cmake \
    libidn11 perl-doc liblmdb-dev wget libsqlite3-dev libgomp1 libjson-perl parallel vmtouch cpanminus python3-pip texlive-latex-base vim && \
    rm -rf /var/lib/apt/lists/* && \
    cpanm HTML::Entities

#WORKDIR /home/root/

#RUN sh -c "$(curl -fsSL https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/install-edirect.sh)"
#ENV PATH="/home/root/edirect:${PATH}"

WORKDIR /opt/

RUN wget https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.tar.gz && \
    gunzip -c edirect.tar.gz | tar xf - && \
    rm -rf edirect.tar.gz

ENV PATH="${PATH}:/opt/edirect"

# Download and build ncbi-vdb
RUN wget https://github.com/ncbi/ncbi-vdb/archive/refs/tags/${vdb_version}.tar.gz && \
    tar xfz ${vdb_version}.tar.gz && rm ${vdb_version}.tar.gz && \
    mv ncbi-vdb-${vdb_version} ncbi-vdb && \
    cd ncbi-vdb && ./configure --prefix /opt/vdb --relative-build-out-dir /opt/ncbi-outdir --build-prefix /opt/ncbi-outdir && make install -j ${num_proc}

# Arrange ncbi-vdb libraries and header files in a form that C++ toolkit
# build can consume them.
ARG VDB=/opt/VDB
RUN mkdir -p ${VDB}/linux/release/x86_64/lib && \
    cp -R /opt/vdb/lib64/* ${VDB}/linux/release/x86_64/lib && \
    cp -R /opt/vdb/lib64/* /blast/lib/ && \
    mkdir -p ${VDB}/interfaces && cp -R /opt/vdb/include/* ${VDB}/interfaces

# -H 'Cache-Control: no-cache, no-store'
# Build BLAST binaries
RUN curl -sS https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${blast_version}/ncbi-blast-${blast_version}+-src.tar.gz | \
    tar xvzf - && \
    cd ncbi-blast-${blast_version}+-src/c++ && \
    ./configure --with-mt --with-strip --with-optimization --with-dll --with-experimental=Int8GI --with-flat-makefile --with-openmp --with-sqlite3 --with-vdb=${VDB} --without-gnutls --without-gcrypt --without-zstd --without-lzo --prefix=/blast && \
    cd ReleaseMT/build && \
    make -j ${num_procs} -f Makefile.flat blastdb_aliastool.exe blastdbcheck.exe blastdbcmd.exe blast_formatter.exe blastn.exe blastp.exe blastx.exe convert2blastmask.exe deltablast.exe dustmasker.exe makeblastdb.exe makembindex.exe makeprofiledb.exe psiblast.exe rpsblast.exe rpstblastn.exe segmasker.exe tblastn.exe tblastx.exe windowmasker.exe blastn_vdb.exe tblastn_vdb.exe blast_formatter_vdb.exe blast_vdb_cmd.exe blastdb_path.exe
RUN find /opt/ncbi-blast-${blast_version}+-src/c++/ReleaseMT && \
    cp -pv /opt/ncbi-blast-${blast_version}+-src/c++/ReleaseMT/bin/* /blast/bin/ && \
    cp -pv /opt/ncbi-blast-${blast_version}+-src/c++/ReleaseMT/lib/* /blast/lib/

RUN mkdir -p /blast/blastdb /blast/blastdb_custom
RUN sed -i '$ a BLASTDB=/blast/blastdb:/blast/blastdb_custom' /etc/environment
ENV BLASTDB /blast/blastdb:/blast/blastdb_custom
ENV BLAST_DOCKER true
ENV PATH="/opt/edirect:/blast/bin:${PATH}"

RUN cp  /blast/bin/blastp /blast/bin/blastp.REAL && \
    cp  /blast/bin/blastn /blast/bin/blastn.REAL && \
    cp  /blast/bin/blastx /blast/bin/blastx.REAL && \
    cp  /blast/bin/tblastn /blast/bin/tblastn.REAL && \
    cp  /blast/bin/tblastx /blast/bin/tblastx.REAL

COPY blastn.sh /blast/bin/blastn
COPY blastp.sh /blast/bin/blastp
COPY blastx.sh /blast/bin/blastx
COPY tblastn.sh /blast/bin/tblastn
COPY tblastx.sh /blast/bin/tblastx

RUN chmod +x /blast/bin/blastn && chmod +x /blast/bin/blastp && \
    chmod +x /blast/bin/blastx && chmod +x /blast/bin/tblastn && \
    chmod +x /blast/bin/tblastx

RUN curl https://sdk.cloud.google.com > install.sh && bash install.sh --disable-prompts --install-dir=/opt && rm -rf /opt/install.sh
ENV PATH="${PATH}:/opt/google-cloud-sdk/bin"

RUN rm -rf /opt/ncbi-blast-${version}+-src
RUN apt-get update && apt-get install -y wget zip libglib2.0-0 libnss3 libdbus-1-3 libatk-bridge2.0-0 libcups2 libdrm-dev libxcomposite-dev \
    libxdamage-dev libxrandr-dev libgbm-dev libxkbcommon-dev libpango-1.0-0 libcairo2-dev libasound2 python3-pip && \
    apt-get clean all && apt-get purge && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

WORKDIR /usr/local

RUN wget https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.78/linux64/chrome-linux64.zip && \
    wget https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.78/linux64/chromedriver-linux64.zip

RUN unzip chrome-linux64.zip && unzip chromedriver-linux64.zip && rm -rf *.zip
RUN pip3 install pandas bs4 selenium html_table_parser biopython

COPY reference/Reference_MN908947.fa /blast/blastdb/.
WORKDIR /blast/blastdb
RUN makeblastdb -in /blast/blastdb/Reference_MN908947.fa -input_type fasta -dbtype nucl -title Wuhan_Hu_1 -parse_seqids -out Wuhan_Hu_1

ADD jalview/ /opt/jalview/
ADD main/ /opt/main/

COPY .jalview_properties /root

RUN ln -s /opt/jalview/bin/jalview.sh /usr/local/bin/jalview

COPY reference /home/root/reference
COPY entrypoint.sh /opt/main/

RUN mkdir /home/root/tmp /home/root/tmp/alignment

WORKDIR /home/root

## covid:0.0.2
# CMD ["/bin/bash"]
# docker run --rm -it -v /disk3/sm/COO/covid/docker/bundle:/files -v /disk3/sm/COO/covid/docker/sequence:/home/root/sequence -v /disk3/sm/COO/covid/TEST:/home/root/work covid:0.0.2


## covid:0.0.1
ENTRYPOINT [ "bash", "/opt/main/entrypoint.sh" ]




# docker run --rm -v /disk3/sm/COO/covid/docker/bundle:/files -v /disk3/sm/COO/covid/docker/sequence:/home/root/sequence -v /disk3/sm/COO/covid/TEST:/home/root/work covid:0.0.1 /home/root/work/multi_test.fa
